### ISSUE TITLE
Webhooks class is missing

### ISSUE THREAD

**Issue by iSunRise** [payload-code/payload-ruby#1]
[According to the docs](https://docs.payload.co/?ruby#webhook-triggers), there must be a class that allows to manipulate webhooks triggers but it is missing. Code example does not work.

It looks like one line fix, I would appreciate it if you do it so I can use your gem instead of my fork.

Thanks

**Comment by ianhalpern** [comment]
@iSunRise thanks for reporting the issue, we've published a new gem with this object included.
